### ISSUE TITLE
Implement a Registration Error for Non-Free Plans

### ISSUE THREAD

**Issue by seanbsu** [seanbsu/ChartCare#28]
### Objective:
Create an error message to be displayed on the registration form when a user attempts to register for a non-free plan. This error will be removed in future releases as the features for these plans are implemented.

### Requirements:
- Perform the check before creating the company record in the database.
- Optionally, include client-side validation to display the error before the form is submitted.

**Comment by LeeMclafferty** [comment]
Can you assign this to me? I will give it a shot.

**Comment by seanbsu** [comment]
you got it
